# Generated by Django 3.1.2 on 2021-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210413_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(default='https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg'),
        ),
    ]
