# Generated by Django 3.1.2 on 2021-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210417_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('H', 'Hoodies')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(default='hoodies/hoodies1', max_length=300),
        ),
    ]
