# Generated by Django 3.1.2 on 2021-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210419_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(default='hoodies/hoodies1.jpg', max_length=300),
        ),
    ]
