# Generated by Django 3.1.2 on 2021-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_orderitem_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='session',
        ),
        migrations.AddField(
            model_name='item',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='item',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='item',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
