# Generated by Django 3.1.2 on 2021-05-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_item_additional_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
